version: '3'
services:
  db_postgres_github-ci:
    image: postgres
    container_name: db_postgres_github-ci
    restart: always
    ports:
      - 5566:5432
    env_file:
      - .env.test

  node_app_github-ci:
    container_name: node_app_github-ci
    build: .
    ports:
      - 5000:5000
    env_file:
      - .env.test
    depends_on:
      - db_postgres_github-ci